version: '3.8'

services:
  nginx:
    build: nginx
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - php8.1
      - php7.4
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./src/:/var/www/

  php8.1:
    build: php8.1
    container_name: php8.1-container
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./src/:/var/www/

  php7.4:
    build: php7.4
    restart: unless-stopped
    container_name: php7.4-container
    expose:
      - 9000
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./src/:/var/www/

  mysql_db:
    image: mysql
    container_name: dev-mysql-container
    ports:
      - 3307:3306
    restart: unless-stopped
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root